# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_calibration1(object):
    def setupUi(self, calibration1):
        calibration1.setObjectName("calibration1")
        calibration1.resize(640, 480)
        self.next1 = QtWidgets.QPushButton(calibration1)
        self.next1.setGeometry(QtCore.QRect(490, 430, 99, 30))
        self.next1.setObjectName("next1")
        self.layoutWidget = QtWidgets.QWidget(calibration1)
        self.layoutWidget.setGeometry(QtCore.QRect(140, 0, 471, 104))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(50, 10, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.verticalLayout_3.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.layoutWidget_2 = QtWidgets.QWidget(calibration1)
        self.layoutWidget_2.setGeometry(QtCore.QRect(0, 0, 141, 473))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(50, 10, 0, 0)
        self.verticalLayout_2.setSpacing(20)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.labelZMove_2 = QtWidgets.QLabel(self.layoutWidget_2)
        self.labelZMove_2.setMaximumSize(QtCore.QSize(120, 40))
        self.labelZMove_2.setObjectName("labelZMove_2")
        self.verticalLayout_2.addWidget(self.labelZMove_2)
        self.zPos11 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.zPos11.setMinimumSize(QtCore.QSize(90, 60))
        self.zPos11.setObjectName("zPos11")
        self.verticalLayout_2.addWidget(self.zPos11)
        self.zPos1 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.zPos1.setEnabled(True)
        self.zPos1.setMinimumSize(QtCore.QSize(90, 60))
        self.zPos1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zPos1.setMouseTracking(False)
        self.zPos1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.zPos1.setArrowType(QtCore.Qt.NoArrow)
        self.zPos1.setObjectName("zPos1")
        self.verticalLayout_2.addWidget(self.zPos1)
        spacerItem = QtWidgets.QSpacerItem(20, 100, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_2.addItem(spacerItem)
        self.zNeg1 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.zNeg1.setEnabled(True)
        self.zNeg1.setMinimumSize(QtCore.QSize(90, 60))
        self.zNeg1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zNeg1.setMouseTracking(False)
        self.zNeg1.setArrowType(QtCore.Qt.NoArrow)
        self.zNeg1.setObjectName("zNeg1")
        self.verticalLayout_2.addWidget(self.zNeg1)
        self.zNeg11 = QtWidgets.QToolButton(self.layoutWidget_2)
        self.zNeg11.setMinimumSize(QtCore.QSize(90, 60))
        self.zNeg11.setObjectName("zNeg11")
        self.verticalLayout_2.addWidget(self.zNeg11)
        self.confirmZ1 = QtWidgets.QToolButton(calibration1)
        self.confirmZ1.setGeometry(QtCore.QRect(190, 210, 141, 91))
        self.confirmZ1.setObjectName("confirmZ1")

        self.retranslateUi(calibration1)
        QtCore.QMetaObject.connectSlotsByName(calibration1)

    def retranslateUi(self, calibration1):
        _translate = QtCore.QCoreApplication.translate
        calibration1.setWindowTitle(_translate("calibration1", "Dialog"))
        self.next1.setText(_translate("calibration1", "Next"))
        self.label.setText(_translate("calibration1", "Calibration step 1"))
        self.label_2.setText(_translate("calibration1", "Jog the Z axis up and down until cells are clearly visible"))
        self.label_3.setText(_translate("calibration1", "When you are ready, click confirm "))
        self.labelZMove_2.setText(_translate("calibration1", "Z Movement"))
        self.zPos11.setText(_translate("calibration1", "+ +"))
        self.zPos1.setText(_translate("calibration1", "+"))
        self.zNeg1.setText(_translate("calibration1", "-"))
        self.zNeg11.setText(_translate("calibration1", "- -"))
        self.confirmZ1.setText(_translate("calibration1", "Confirm Z Value"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    calibration1 = QtWidgets.QDialog()
    ui = Ui_calibration1()
    ui.setupUi(calibration1)
    calibration1.show()
    sys.exit(app.exec_())
